### ISSUE TITLE
Glyphs Disappearing When Working in Adobe Illustrator

### ISSUE THREAD

**Issue by Kaktug** [graphicore/librebarcode#17]
Hi all 👋 ,

Not sure how active this project is, but, figured I'd open an issue for a problem I've run into.  Specifically, I'd like to use the Libre Barcode fonts inside Adobe Illustrator.  However, when I try to convert the text objects to outlines (pure vector shapes), some of the barcode glyphs disappear.  You can see this in the screenshot below:
![missing_glyphs](https://user-images.githubusercontent.com/17927046/58507199-2ee2c300-815f-11e9-8873-6d98291c04c3.png)

On the left are 3 rows of pure text frames (mixed case, uppercase, lowercase respectively)
On the right are those same 3 rows after converting to vector shapes.  You can see the barcode stripes change pretty dramatically, with the ones that fill in the gaps disappearing entirely.

Any idea why this might be?  I've tried fiddling with some of the character panel settings in Illustrator without success.

**Comment by graphicore** [comment]
Hi @Kaktug. Sorry for the late reply! This somehow slipped under my radar.

It seems like Illustrator is being "smart" here and not converting the space glyph because it shouldn't draw anything anyway ...

I'm not sure what can be done here reasonably from this project.

You could try to build your own version of the font, where the space char also maps to some unicode and then use that unicode in your text.

**Comment by Kaktug** [comment]
Hey @graphicore !

Thanks for getting back to me and for the suggestion.  I'm going to close this issue, I ended up coming to the same conclusion as you did after doing some more testing.  Seems like this is really just down to how Illustrator manages space glyphs.  If it means anything, we're totally happy with this set of fonts, so thank you!

**Comment by graphicore** [comment]
Thanks!
