### ISSUE TITLE
EAN13 *without* Text

### ISSUE THREAD

**Issue by pomjuice** [graphicore/librebarcode#36]
Is there any way to make an EAN13 font without text?

**Comment by graphicore** [comment]
I didn't do it because it's not part of the standard. There are a lot of layout (bar-height) adjustments around the text, which are part of the standard, e.g. for add-ons and guard-symbols. The font itself and the generating code could be much simpler without text below, but enabling both modes in the same code in a clean way is some effort, given that there's no standard for these codes without text below.

> Is there any way to make an EAN13 font without text?

I'm sure there are many ways. Can't say if it will be quick. Changing the builder code would need some effort.

What is your use case?
If I could e.g. control HTML/CSS, I'd try to cut off the parts with text that I don't want, based on CSS `overflow: hidden`.

**Comment by graphicore** [comment]
@pomjuice I'm going to close this issue soon as I can't do anything without a conversation.

**Comment by pomjuice** [comment]
I understand why.
It is a great font that is easy to use, very helpful, thank you!
