### ISSUE TITLE
Code 128 Font not rendering the same as on Libre Barcode project page

### ISSUE THREAD

**Issue by brittadams** [graphicore/librebarcode#42]
Code 128 Font not rendering the same as on Libre Barcode project page, tried both the downlead from the project and google. Google does not render it properly either. 
![2021-06-04 14_17_08-Code 128 _ Libre Barcode Project - Brave](https://user-images.githubusercontent.com/3202129/120864264-cb0ae600-c540-11eb-95e0-d7dd711b6822.png)
![2021-06-04 14_17_16-Libre Barcode 128 Text - Google Fonts - Brave](https://user-images.githubusercontent.com/3202129/120864267-ccd4a980-c540-11eb-8037-8744b973cca4.png)

**Comment by graphicore** [comment]
Hie @brittadams , thanks for reporting! However, the information provided is a little sparse, please give me more context: Where did you try it, which software, which OS? What was your original input string? How can I reproduce this issue? What is your expected result?

**Comment by brittadams** [comment]
@graphicore The first image is from your github encoder https://graphicore.github.io/librebarcode/documentation/code128 which displays the proper barcode and the scanners I tested worked. The other one is the result on the google font library https://fonts.google.com/specimen/Libre+Barcode+128. When I download your font on windows it looks like the one from google not the one on your encoder page and does not work with any scanners. Other online barcode generators look like your encoder page and work as well https://barcode.tec-it.com/en/Code128?data=4523

**Comment by graphicore** [comment]
@brittadams I think there's a little misunderstanding on how the encoder works:

![Screenshot from 2021-06-07 16-51-53](https://user-images.githubusercontent.com/393132/121038777-d7957580-c7b0-11eb-815a-9e1348046c20.png)

The input text of the encoder is `5423` but it says at the bottom "*Copy the encoded text to use it with one of the Libre Barcode 128 fonts:*"

and then it displays the output as `ÍV7ÊÎ`

When I use that output on [Google Fonts](https://fonts.google.com/specimen/Libre+Barcode+128+Text?preview.text=%C3%8DV7%C3%8A%C3%8E&preview.text_type=custom) I get:

![Screenshot from 2021-06-07 16-56-08](https://user-images.githubusercontent.com/393132/121039332-48d52880-c7b1-11eb-90ae-edce6e719184.png)

That's why there is a need for an encoder at all, because the input text to the font is not the same as data that is encoded.

**Comment by nemus9** [comment]
When I put the encoded text for the number 5423, ÍV7ÊÎ, in a word document and then change the font to Libre Barcode 128 Text, I see V7 in the text under the barcode instead of 5423. How to get the font to show 5423 instead of the encoded text?

![Screenshot 2021-06-26 114647](https://user-images.githubusercontent.com/57599285/123522765-48270800-d674-11eb-88c9-8134a5b2ac1b.png)

**Comment by graphicore** [comment]
@nemus9 sorry for the late reply, I missed your question.

> In Word, deep down in the style menu you must activate "Use Contextual Alternates" under e.g.:
>
> Apply Styles -> Modify … -> Format … -> Font … -> Advanced

Here's a screenshot: https://github.com/graphicore/librebarcode/issues/28#issuecomment-745736391

**Comment by graphicore** [comment]
@nemus9 @brittadams Any more feedback or can this issue be closed?

**Comment by nemus9** [comment]
Thanks for the information on how to view the unencoded text for barcode 128 text. Good to know!
