### ISSUE TITLE
Feature Request: Bulk Encoder

### ISSUE THREAD

**Issue by graphicore** [graphicore/librebarcode#52]
I received this via Email, removed personal information:

> Dear Lasse,
>
>First of all, I'm very sorry to bother you in this rather rude manner, but I hope you can help me solve an issue.
>
>I need to create a lot of EAN13 barcodes through Adobe Illustrator/indesign with the datamerge function. Through some extensive googling, I found the graphicore Libre Barcode EAN13 font and the EAN13 encoder (https://graphicore.github.io/librebarcode/documentation/ean13.html#ean13-encoder) which work like charm. The one problem I'm having is that I have to manually translate every code to Fallback or Compatible code through the mentioned encoder, which is a pain in the ....
>
>Is there any way you can help me to translate a large list of numbers to Fallback or Compatible code?
>
>Thanks a million in advance!

**Comment by graphicore** [comment]
Fixed, online at https://graphicore.github.io/librebarcode/documentation/ean13-bulk.html

**Comment by xUltraICE** [comment]
Hey Graphicore,

I hope this message finds you well.

As the original poster (OP), I conducted thorough research and came across your project.
I must say, it's an excellent project and has proven to be incredibly useful.

In order to minimize human error tho (copy from excel to bulk encoder, back to excel), I would like to ask you if you think it's possible to have a visual basic formula to translate the OG data string to the encoded string from a column to another?

Something similar to the one provided by Grandzebu.
I noticed that that works only for EAN13, or a 12 digits number (EAN w/o checksum), but not for UPC-A (11 digits).

Looking forward to hearing your thoughts on this.
